/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ontapmuc1_cau11_caro;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ADMIN
 */
public class Caro extends javax.swing.JFrame {

    int x_or_o = 0;
    int winX = 0;
    int winO = 0;
    public Caro() {
        initComponents();
        addAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtWinOfNumberX = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtWinOfNumberO = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 5, 5));
        jPanel1.add(bt1);
        jPanel1.add(bt2);
        jPanel1.add(bt3);
        jPanel1.add(bt4);
        jPanel1.add(bt5);
        jPanel1.add(bt6);
        jPanel1.add(bt7);
        jPanel1.add(bt8);
        jPanel1.add(bt9);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caro 3x3");

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("player X");
        jPanel2.add(jLabel2);

        txtWinOfNumberX.setBackground(new java.awt.Color(204, 0, 51));
        txtWinOfNumberX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtWinOfNumberX.setForeground(new java.awt.Color(255, 51, 51));
        txtWinOfNumberX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWinOfNumberX.setText("0");
        jPanel2.add(txtWinOfNumberX);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("player O");
        jPanel2.add(jLabel4);

        txtWinOfNumberO.setBackground(new java.awt.Color(204, 0, 51));
        txtWinOfNumberO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtWinOfNumberO.setForeground(new java.awt.Color(255, 51, 51));
        txtWinOfNumberO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWinOfNumberO.setText("0");
        jPanel2.add(txtWinOfNumberO);

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        jPanel2.add(btReset);

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel2.add(btExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        Component[] comps = jPanel1.getComponents();
        
        for (Component comp : comps) {
            if (comp instanceof JButton){
                JButton button = (JButton)comp;
                button.setText("");
                button.setBackground(Color.WHITE);
                x_or_o = 0;
            }
        }
    }//GEN-LAST:event_btResetActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btExitActionPerformed
    
    
    //hiện thị màu
    public void winEffect(JButton button1, JButton button2, JButton button3){
        button1.setBackground(Color.black);
        button2.setBackground(Color.black);
        button3.setBackground(Color.black);
        
        button1.setForeground(Color.WHITE);
        button2.setForeground(Color.WHITE);
        button3.setForeground(Color.WHITE);
    }
    
    public boolean getTheWinner(){
        String[][] board = new String[3][3];
        board[0][0] = bt1.getText();
        board[0][1] = bt2.getText();
        board[0][2] = bt3.getText();
        board[1][0] = bt4.getText();
        board[1][1] = bt5.getText();
        board[1][2] = bt6.getText();
        board[2][0] = bt7.getText();
        board[2][1] = bt8.getText();
        board[2][2] = bt9.getText();

        // Kiểm tra các hàng
        for (int i = 0; i < 3; i++) {
            if (!board[i][0].equals("") && board[i][0].equals(board[i][1]) && board[i][1].equals(board[i][2])) {
                return true;
            }
        }

        // Kiểm tra các cột
        for (int j = 0; j < 3; j++) {
            if (!board[0][j].equals("") && board[0][j].equals(board[1][j]) && board[1][j].equals(board[2][j])) {
                return true;
            }
        }

        // Kiểm tra đường chéo chính
        if (!board[0][0].equals("") && board[0][0].equals(board[1][1]) && board[1][1].equals(board[2][2])) {
            return true;
        }

        // Kiểm tra đường chéo phụ
        if (!board[0][2].equals("") && board[1][1].equals(board[0][2]) && board[2][0].equals(board[0][2])) {
            return true;
        }
        return false;
    }
    
    public void getTheDraw(){
        
    }
    
    public ActionListener createAction(JButton button){
        ActionListener a1 = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (button.getText().equals("") && !getTheWinner()){
                    if (x_or_o % 2 == 0){
                        button.setText("X");
                        button.setForeground(Color.blue);
                        if (getTheWinner()){
                            winX++;
                            txtWinOfNumberX.setText("" + winX);
                        }
                        getTheDraw();
                    }else{
                        button.setText("O");
                        button.setForeground(Color.red);
                        if (getTheWinner()){
                            winO++;
                            txtWinOfNumberO.setText("" + winO);
                        }
                        getTheDraw();
                    }
                    x_or_o++;
                }
            }
            
        };
        return a1;
    }
    
    public void addAction(){
        Component[] comps = jPanel1.getComponents();
        
        for (Component comp : comps) {
            if (comp instanceof JButton){
                JButton button = (JButton)comp;
                button.addActionListener(createAction(button));
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtWinOfNumberO;
    private javax.swing.JLabel txtWinOfNumberX;
    // End of variables declaration//GEN-END:variables
}
